data:
  dataset: mnist
  transforms:
    main:
      - Normalize
      - ToTensorV2
    strong:
      strong:
        - GridDistortion:
            - num_steps: 4
            - p: 0.75
        - Flip
        - p: 1.0

model:
  name: classifier
  input_dim: 784
  hidden_dim: 128 # ToTune
  num_classes: 10
  encoder_weights: "logs/autoencoder/best_weights.pth"

loss: ce

optimizer:
  name: Adam
  lr: 0.001

runner:
  dataset_dir: "data/MNIST"
  batch_size: 32
  logdir: "logs/classifer/"
  num_epochs: 100
  device: "cuda"

inference:
  batch_size: 4
  weights: "logs/autoencoder/best_weights.pth"