data:
  dataset: mnist

model:
  name: classifier
  input_dim: 784
  hidden_dim: 10
  num_classes: 10
  encoder_weights: "logs/autoencoder_10/checkpoints/best_weights.pth"
  weigths: None
  freeze_encoder: True

loss: ce

optimizer:
  name: Adam
  lr: 0.001

runner:
  dataset_dir: "data/MNIST"
  batch_size: 32
  logdir: "logs/classifer_10/"
  num_epochs: 100
  device: "cuda"

inference:
  batch_size: 4
  weights: "logs/classifer_10/checkpoints/best_weights.pth"
